services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: alerta_doador-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - alerta_doador
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: alerta_doador-backend
    container_name: alerta_doador-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - db
    networks:
        - alerta_doador
    working_dir: /app/src
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    image: alerta_doador-frontend
    container_name: alerta_doador-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - alerta_doador
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:

networks:
  alerta_doador:
    name: alerta_doador  # Isso força o nome da rede a ser EXATAMENTE este
    driver: bridge