name: Lint and Format

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github ."
          
      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."
